<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="12" ignored="24" total="54" passed="18">
  <reporter-output>
  </reporter-output>
  <suite name="Trainer Tests" duration-ms="171240" started-at="2018-02-21T14:51:16Z" finished-at="2018-02-21T14:54:07Z">
    <groups>
    </groups>
    <test name="Test Home Tab" duration-ms="4734" started-at="2018-02-21T14:51:16Z" finished-at="2018-02-21T14:51:21Z">
      <class name="com.revature.test.admin.testclasses.HomeTest">
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.HomeTest@5b38c1ec]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:51:16Z" finished-at="2018-02-21T09:51:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="NavigateToHomeTab()[pri:0, instance:com.revature.test.admin.testclasses.HomeTest@5b38c1ec]" name="NavigateToHomeTab" duration-ms="2294" started-at="2018-02-21T09:51:16Z" finished-at="2018-02-21T09:51:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToHomeTab -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.HomeTest@5b38c1ec]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:51:18Z" finished-at="2018-02-21T09:51:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="clickEmail()[pri:2, instance:com.revature.test.admin.testclasses.HomeTest@5b38c1ec]" name="clickEmail" duration-ms="1186" started-at="2018-02-21T09:51:18Z" finished-at="2018-02-21T09:51:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickEmail -->
        <test-method status="PASS" signature="clickWebSite()[pri:3, instance:com.revature.test.admin.testclasses.HomeTest@5b38c1ec]" name="clickWebSite" duration-ms="1204" started-at="2018-02-21T09:51:20Z" finished-at="2018-02-21T09:51:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickWebSite -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.HomeTest@5b38c1ec]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:51:20Z" finished-at="2018-02-21T09:51:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.revature.test.admin.testclasses.HomeTest@5b38c1ec]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-02-21T09:51:21Z" finished-at="2018-02-21T09:51:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.revature.test.admin.testclasses.HomeTest -->
    </test> <!-- Test Home Tab -->
    <test name="Test Client List Tab" duration-ms="40389" started-at="2018-02-21T14:51:21Z" finished-at="2018-02-21T14:52:01Z">
      <class name="com.revature.test.admin.testclasses.ClientListTest">
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:51:21Z" finished-at="2018-02-21T09:51:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="NavigateToCreateUserTab()[pri:0, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="NavigateToCreateUserTab" duration-ms="7729" started-at="2018-02-21T09:51:21Z" finished-at="2018-02-21T09:51:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToCreateUserTab -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:51:29Z" finished-at="2018-02-21T09:51:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="FAIL" signature="SearchAndViewClientData()[pri:1, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="SearchAndViewClientData" duration-ms="11205" started-at="2018-02-21T09:51:29Z" finished-at="2018-02-21T09:51:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: Failed to search client by name and view their data]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: Failed to search client by name and view their dataat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.ClientListTest.SearchAndViewClientData(ClientListTest.java:56)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchAndViewClientData -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:51:40Z" finished-at="2018-02-21T09:51:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="ViewAllClientData()[pri:2, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="ViewAllClientData" duration-ms="870" started-at="2018-02-21T09:51:40Z" finished-at="2018-02-21T09:51:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ViewAllClientData -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:51:41Z" finished-at="2018-02-21T09:51:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="FAIL" signature="ClickAndViewClientData()[pri:3, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="ClickAndViewClientData" duration-ms="2466" started-at="2018-02-21T09:51:41Z" finished-at="2018-02-21T09:51:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: Failed to select client from list and view their data]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: Failed to select client from list and view their dataat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.ClientListTest.ClickAndViewClientData(ClientListTest.java:81)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ClickAndViewClientData -->
        <test-method status="FAIL" signature="SearchButSearchAnotherAndViewClientData()[pri:4, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="SearchButSearchAnotherAndViewClientData" duration-ms="9410" started-at="2018-02-21T09:51:43Z" finished-at="2018-02-21T09:51:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: Failed to search client by name but then search another client name and view their data]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: Failed to search client by name but then search another client name and view their dataat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.ClientListTest.SearchButSearchAnotherAndViewClientData(ClientListTest.java:98)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchButSearchAnotherAndViewClientData -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:51:43Z" finished-at="2018-02-21T09:51:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:51:53Z" finished-at="2018-02-21T09:51:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="SearchButClickViewAllClientData()[pri:5, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="SearchButClickViewAllClientData" duration-ms="3592" started-at="2018-02-21T09:51:53Z" finished-at="2018-02-21T09:51:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchButClickViewAllClientData -->
        <test-method status="FAIL" signature="SearchButClickClientAndViewClientData()[pri:6, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="SearchButClickClientAndViewClientData" duration-ms="5089" started-at="2018-02-21T09:51:56Z" finished-at="2018-02-21T09:52:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: Failed to search client by name but then select client from list and view their data]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: Failed to search client by name but then select client from list and view their dataat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.ClientListTest.SearchButClickClientAndViewClientData(ClientListTest.java:127)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchButClickClientAndViewClientData -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:51:56Z" finished-at="2018-02-21T09:51:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.revature.test.admin.testclasses.ClientListTest@60f00693]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-02-21T09:52:01Z" finished-at="2018-02-21T09:52:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.revature.test.admin.testclasses.ClientListTest -->
    </test> <!-- Test Client List Tab -->
    <test name="Test Batch List Tab" duration-ms="44918" started-at="2018-02-21T14:52:01Z" finished-at="2018-02-21T14:52:46Z">
      <class name="com.revature.test.admin.testclasses.BatchListTest">
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:52:01Z" finished-at="2018-02-21T09:52:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="NavigateToBatchListTab()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="NavigateToBatchListTab" duration-ms="3238" started-at="2018-02-21T09:52:01Z" finished-at="2018-02-21T09:52:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToBatchListTab -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:52:05Z" finished-at="2018-02-21T09:52:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="FindAllBatchesTag()[pri:1, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="FindAllBatchesTag" duration-ms="1063" started-at="2018-02-21T09:52:05Z" finished-at="2018-02-21T09:52:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FindAllBatchesTag -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:52:06Z" finished-at="2018-02-21T09:52:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="FAIL" signature="BatchNameTest()[pri:2, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="BatchNameTest" duration-ms="30562" started-at="2018-02-21T09:52:06Z" finished-at="2018-02-21T09:52:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: Batch Name Test Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: Batch Name Test Failedat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.BatchListTest.BatchNameTest(BatchListTest.java:58)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BatchNameTest -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:52:36Z" finished-at="2018-02-21T09:52:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="FAIL" signature="InputFromDateFields()[pri:3, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="InputFromDateFields" duration-ms="371" started-at="2018-02-21T09:52:36Z" finished-at="2018-02-21T09:52:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: Could not input a valid date into 'from' date field]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: Could not input a valid date into 'from' date fieldat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.BatchListTest.InputFromDateFields(BatchListTest.java:69)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InputFromDateFields -->
        <test-method status="FAIL" signature="InputToDateFields()[pri:4, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="InputToDateFields" duration-ms="364" started-at="2018-02-21T09:52:37Z" finished-at="2018-02-21T09:52:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: Could not input a valid date into 'to' date field]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: Could not input a valid date into 'to' date fieldat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.BatchListTest.InputToDateFields(BatchListTest.java:79)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InputToDateFields -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:52:37Z" finished-at="2018-02-21T09:52:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="ClickFromField()[pri:5, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="ClickFromField" duration-ms="705" started-at="2018-02-21T09:52:37Z" finished-at="2018-02-21T09:52:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ClickFromField -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:52:37Z" finished-at="2018-02-21T09:52:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="ClickToField()[pri:6, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="ClickToField" duration-ms="1548" started-at="2018-02-21T09:52:38Z" finished-at="2018-02-21T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ClickToField -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:52:38Z" finished-at="2018-02-21T09:52:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:52:39Z" finished-at="2018-02-21T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="ClickSubmit()[pri:7, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="ClickSubmit" duration-ms="145" started-at="2018-02-21T09:52:39Z" finished-at="2018-02-21T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ClickSubmit -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:52:39Z" finished-at="2018-02-21T09:52:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="areResultsCorrect()[pri:8, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="areResultsCorrect" duration-ms="161" started-at="2018-02-21T09:52:39Z" finished-at="2018-02-21T09:52:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- areResultsCorrect -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:52:40Z" finished-at="2018-02-21T09:52:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="ClickReset()[pri:9, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="ClickReset" duration-ms="184" started-at="2018-02-21T09:52:40Z" finished-at="2018-02-21T09:52:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ClickReset -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:52:40Z" finished-at="2018-02-21T09:52:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="allBatchesShowing()[pri:10, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="allBatchesShowing" duration-ms="1115" started-at="2018-02-21T09:52:40Z" finished-at="2018-02-21T09:52:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- allBatchesShowing -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:52:41Z" finished-at="2018-02-21T09:52:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="useCase1()[pri:11, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="useCase1" duration-ms="5422" started-at="2018-02-21T09:52:41Z" finished-at="2018-02-21T09:52:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- useCase1 -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.revature.test.admin.testclasses.BatchListTest@4b520ea8]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-02-21T09:52:46Z" finished-at="2018-02-21T09:52:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.revature.test.admin.testclasses.BatchListTest -->
    </test> <!-- Test Batch List Tab -->
    <test name="Test Associate List Tab" duration-ms="12565" started-at="2018-02-21T14:52:46Z" finished-at="2018-02-21T14:52:59Z">
      <class name="com.revature.test.admin.testclasses.AssociateListTest">
        <test-method status="PASS" signature="NavigateToAssociateListTab()[pri:0, instance:com.revature.test.admin.testclasses.AssociateListTest@1b1cfb87]" name="NavigateToAssociateListTab" duration-ms="2231" started-at="2018-02-21T09:52:46Z" finished-at="2018-02-21T09:52:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToAssociateListTab -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.AssociateListTest@1b1cfb87]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:52:46Z" finished-at="2018-02-21T09:52:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="EditAssociateInformation()[pri:21, instance:com.revature.test.admin.testclasses.AssociateListTest@1b1cfb87]" name="EditAssociateInformation" duration-ms="10328" started-at="2018-02-21T09:52:49Z" finished-at="2018-02-21T09:52:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EditAssociateInformation -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.AssociateListTest@1b1cfb87]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:52:49Z" finished-at="2018-02-21T09:52:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.revature.test.admin.testclasses.AssociateListTest@1b1cfb87]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-02-21T09:52:59Z" finished-at="2018-02-21T09:52:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.revature.test.admin.testclasses.AssociateListTest -->
    </test> <!-- Test Associate List Tab -->
    <test name="Test Create User Tab" duration-ms="68301" started-at="2018-02-21T14:52:59Z" finished-at="2018-02-21T14:54:07Z">
      <class name="com.revature.test.admin.testclasses.CreateUserTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="beforeSuite" is-config="true" duration-ms="6581" started-at="2018-02-21T09:51:09Z" finished-at="2018-02-21T09:51:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="NavigateToCreateUserTest()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="NavigateToCreateUserTest" is-config="true" duration-ms="2295" started-at="2018-02-21T09:52:59Z" finished-at="2018-02-21T09:53:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToCreateUserTest -->
        <test-method status="PASS" signature="RunningCreateUserTabTests()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="RunningCreateUserTabTests" duration-ms="1" started-at="2018-02-21T09:53:01Z" finished-at="2018-02-21T09:53:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RunningCreateUserTabTests -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:53:01Z" finished-at="2018-02-21T09:53:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="NavigateToCreateUserTest()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="NavigateToCreateUserTest" is-config="true" duration-ms="2137" started-at="2018-02-21T09:53:01Z" finished-at="2018-02-21T09:53:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToCreateUserTest -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:53:03Z" finished-at="2018-02-21T09:53:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="FAIL" signature="CreateAdmin()[pri:1, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="CreateAdmin" duration-ms="12944" started-at="2018-02-21T09:53:03Z" finished-at="2018-02-21T09:53:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: Failed to create new Administrater]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: Failed to create new Administraterat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.CreateUserTest.CreateAdmin(CreateUserTest.java:69)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateAdmin -->
        <test-method status="PASS" signature="NavigateToCreateUserTest()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="NavigateToCreateUserTest" is-config="true" duration-ms="2202" started-at="2018-02-21T09:53:16Z" finished-at="2018-02-21T09:53:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToCreateUserTest -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:53:19Z" finished-at="2018-02-21T09:53:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="FAIL" signature="CreateManager()[pri:2, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="CreateManager" duration-ms="12870" started-at="2018-02-21T09:53:19Z" finished-at="2018-02-21T09:53:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: Failed to create new Manager]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: Failed to create new Managerat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.CreateUserTest.CreateManager(CreateUserTest.java:86)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateManager -->
        <test-method status="PASS" signature="NavigateToCreateUserTest()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="NavigateToCreateUserTest" is-config="true" duration-ms="2126" started-at="2018-02-21T09:53:31Z" finished-at="2018-02-21T09:53:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToCreateUserTest -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="TestInfo" is-config="true" duration-ms="1" started-at="2018-02-21T09:53:34Z" finished-at="2018-02-21T09:53:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="FAIL" signature="CreateVP()[pri:3, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="CreateVP" duration-ms="12849" started-at="2018-02-21T09:53:34Z" finished-at="2018-02-21T09:53:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: Failed to create new Vice President]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: Failed to create new Vice Presidentat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.CreateUserTest.CreateVP(CreateUserTest.java:103)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateVP -->
        <test-method status="PASS" signature="NavigateToCreateUserTest()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="NavigateToCreateUserTest" is-config="true" duration-ms="2151" started-at="2018-02-21T09:53:46Z" finished-at="2018-02-21T09:53:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToCreateUserTest -->
        <test-method status="FAIL" signature="CreateAssociate()[pri:4, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="CreateAssociate" duration-ms="12799" started-at="2018-02-21T09:53:49Z" finished-at="2018-02-21T09:54:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: Failed to create new Associate]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: Failed to create new Associateat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.CreateUserTest.CreateAssociate(CreateUserTest.java:120)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateAssociate -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:53:49Z" finished-at="2018-02-21T09:53:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="NavigateToCreateUserTest()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="NavigateToCreateUserTest" is-config="true" duration-ms="2167" started-at="2018-02-21T09:54:01Z" finished-at="2018-02-21T09:54:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- NavigateToCreateUserTest -->
        <test-method status="FAIL" signature="CreateAssociateDuplicateUsername()[pri:5, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="CreateAssociateDuplicateUsername" duration-ms="3731" started-at="2018-02-21T09:54:04Z" finished-at="2018-02-21T09:54:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error: Failed to create new Associate]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error: Failed to create new Associateat org.testng.Assert.fail(Assert.java:96)at com.revature.test.admin.testclasses.CreateUserTest.CreateAssociateDuplicateUsername(CreateUserTest.java:138)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateAssociateDuplicateUsername -->
        <test-method status="PASS" signature="TestInfo()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="TestInfo" is-config="true" duration-ms="0" started-at="2018-02-21T09:54:04Z" finished-at="2018-02-21T09:54:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestInfo -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-02-21T09:54:07Z" finished-at="2018-02-21T09:54:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.revature.test.admin.testclasses.CreateUserTest@1be2019a]" name="afterSuite" is-config="true" duration-ms="1748" started-at="2018-02-21T09:54:07Z" finished-at="2018-02-21T09:54:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.revature.test.admin.testclasses.CreateUserTest -->
    </test> <!-- Test Create User Tab -->
  </suite> <!-- Trainer Tests -->
</testng-results>
